name: Security Alerts to Slack
on:
  code_scanning_alert:
    types: [created, reopened]
  secret_scanning_alert:
    types: [created, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Alert to Slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "Security Alert Found!",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Security Alert in ${{ github.repository }}*\nEvent: ${{ github.event_name }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
